repos:
  - repo: local
    hooks:
    - id: check-ada-style
      name: Style checking for Ada files
      entry: make check
      language: system
      always_run: true
      pass_filenames: false
    - id: check-opt-syntax
      name: Check opt file syntax
      files: '\.opt$'
      language: system
      entry: e3-opt-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-json
        exclude: ^\.vscode/
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
  - repo: git-adacore:eng/spark/support
    rev: "0.1"
    hooks:
    -   id: check-empty-testoutopt
    -   id: check-testsuite-markers
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black
