repos:
  - repo: local
    hooks:
    -   id: check-ada-style
        name: Style checking for Ada files
        entry: make check
        language: system
        always_run: true
        pass_filenames: false
